# CregisRAG系统配置

# 应用程序设置
app:
  name: "CregisRAG"
  description: "企业级检索增强生成系统"
  version: "0.1.0"
  environment: "development"
  host: "0.0.0.0"
  port: 8000
  debug: true
  cors_origins:
    - "http://localhost:3000"
    - "http://localhost:8000"
    - "http://127.0.0.1:3000"
    - "http://127.0.0.1:8000"
    - "*"  # 开发环境允许所有来源，生产环境应限制

# 前端配置
frontend:
  title: "Cregis RAG 系统"
  description: "检索增强生成系统"
  logo_path: "/static/logo.png"
  theme: "light"
  language: "zh-CN"

# 嵌入服务配置
embedding:
  provider: "zhipuai"
  model: "embedding-3"
  api_key: "${ZHIPUAI_API_KEY}"
  dimension: 1536
  batch_size: 10
  cache_enabled: true
  normalize_embeddings: true
  
  # 文本预处理配置
  text_processor:
    # 常规清洗选项
    remove_urls: true
    remove_html: true
    normalize_whitespace: true
    lowercase: true
    remove_punctuation: false
    # 分词选项
    segmentation_enabled: true
    remove_stopwords: true
    stopwords_file: "data/stopwords/chinese_stopwords.txt"
    # 查询扩展
    query_expansion_enabled: true
    query_rewrite_count: 2

# 存储配置
storage:
  # 向量存储配置
  vector_store:
    provider: "chroma"
    collection_name: "documents"
    persist_directory: "data/chroma"
    embedding_dimension: 1536
  
  # 文本索引配置（可选）
  use_text_index: false
  normalize_embeddings: true
  
  # 目录配置
  data_dir: "data"
  raw_dir: "data/raw"
  processed_dir: "data/processed"
  embeddings_dir: "data/embeddings"

# LLM服务配置
llm:
  provider: "zhipuai"
  model: "glm-4"
  api_key: "${ZHIPUAI_API_KEY}"
  temperature: 0.3
  max_tokens: 2000
  top_p: 0.9
  stop: ["<END>"]

# RAG引擎配置
rag:
  # 检索配置
  similarity_threshold: 0.2
  top_k: 5
  enable_hybrid_search: true
  hybrid_search_weight: 0.3
  enable_reranking: true
  
  # MMR配置（多样性检索）
  use_mmr: true
  mmr_lambda: 0.5
  
  # 自动检测语言
  auto_detect_language: true
  
  # 上下文长度限制
  max_document_length: 8000
  
  # 提示模板
  prompt_template: |
    你是Cregis的AI助手，请根据以下参考文档回答问题。
    如果参考文档中没有包含问题的答案，请说明你无法回答这个问题。
    请不要编造任何不在参考文档中的信息。
    尽可能详细地回答问题，但保持简洁清晰。
    
    参考文档:
    {{documents}}
    
    问题: {{query}}
    
    回答:

# 文档处理配置
document_processing:
  extract_metadata: true
  supported_formats:
    - pdf
    - txt
    - doc
    - docx
    - html
    - md
  chunk_size: 1000
  chunk_overlap: 200
  detect_language: true
  extract_images: false
  pdf_processing:
    use_enhanced_parser: true   # 启用增强的PDF解析器
    fallback_to_pdfplumber: true  # 在PyPDF2解析质量不佳时使用pdfplumber作为后备
    ocr_enabled: false  # OCR功能（可选）
    text_cleaning: true  # 启用文本清理
    x_tolerance: 3  # pdfplumber的x方向容差
    y_tolerance: 3  # pdfplumber的y方向容差

# 文本分块配置
chunker:
  chunk_size: 500
  chunk_overlap: 100
  split_method: "paragraph"
  min_chunk_size: 50

# 文件存储配置
file_storage:
  storage_type: "local"
  local_path: "data/documents"
  max_file_size_mb: 20
  allowed_file_types:
    - "pdf"
    - "docx"
    - "txt"
    - "md"

# 安全配置
security:
  enable_authentication: false
  enable_rate_limiting: true
  rate_limit:
    max_requests: 50
    window_seconds: 60

# 系统配置
system:
  log_level: "INFO"
  log_file: "logs/app.log"
  max_concurrent_tasks: 5

# 摄入服务配置
ingest:
  source_dir: "./data/raw"
  processed_dir: "./data/processed"
  save_processed: true
  batch_size: 10

# 提示模板
prompts:
  system_template: |
    你是一个智能问答助手，请基于提供的文档内容回答问题。
    只回答与提供文档相关的内容，如果不知道答案，请坦诚说明。
    回答应简洁明了，如有必要，可以使用markdown格式化输出。
    
  query_template: |
    基于以下文档内容回答问题:
    
    {context}
    
    问题: {query}
    
    回答:

# 日志配置
logging:
  level: "INFO"  # 日志级别: DEBUG, INFO, WARNING, ERROR
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "data/logs/cregis.log"  # 日志文件
  max_file_size_mb: 10  # 最大日志文件大小(MB)
  backup_count: 5  # 保留的备份日志文件数 